#
# (C) Copyright 2015 Elvees Neotek CJSC
# Vasiliy Zasukhin <vzasukhin@elvees.com>
#
# Based on some other Makefile
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += timer.o board.o sdmmc.o bootrom.o
